/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";

import { useRouter } from "next/router";
import { useState, useRef } from "react";

// Third-Party
import Particles from "react-tsparticles";
import GitHubOAuthButton from "../components/GithubOAuthButton/GithubOAuthButton";

// Constants
import { particleOptions } from "../constants/particleOptions";

export default function Home() {
  // State
  const [username, setUsername] = useState("");

  // References
  const wrapItUpRef = useRef(null);
  const landingFlowBRef = useRef(null);

  // Hooks
  const router = useRouter();

  const handleUserNameChange = (event) => {
    const labelClassList = wrapItUpRef.current.classList;
    const flowBClassList = landingFlowBRef.current.classList;
    const containsText = event.target.value.trim().length > 0;

    if (containsText && labelClassList[0] === "hidden") {
      labelClassList.remove("hidden");
      flowBClassList.add("hidden");
    } else if (!containsText && !labelClassList[0] !== "hidden") {
      labelClassList.add("hidden");
      flowBClassList.remove("hidden");
    }
    setUsername(event.target.value);
  };

  const handleKeyPress = (event) => {
    // Optional attribute for IE
    if (event?.code === "Enter") handleUsernameSubmit();
  };

  const handleUsernameSubmit = (e) => router.push(`/${username}`);

  return (
    <div>
      <Head>
        <title>GitHub Wrapped</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section className="landing">
        <Particles id="tsparticles" options={particleOptions} />
        <Image
          src="/favicon.png"
          className="landing__logo"
          alt="GitHub Wrapped Logo"
          width={54}
          height={54}
        />

        <div className="landing__content">
          <h1 className="landing__title">#GitHubWrapped</h1>
          <div className="landing__message">We&apos;re ready for 2022!</div>
          <p className="landing__text">
            Let&apos;s take a look at all the contributions you made to the
            open-source community in the last 52 weeks!
          </p>

          <div className="landing__flow-a">
            <input
              className="landing__input"
              placeholder="Type your username"
              value={username}
              onChange={handleUserNameChange}
              onSubmit={handleUsernameSubmit}
              onKeyPress={handleKeyPress}
              autoFocus={true}
            />

            <button
              ref={wrapItUpRef}
              className="hidden"
              onClick={handleUsernameSubmit}
            >
              Wrap It Up !
            </button>
          </div>

          <div className="landing__flow-b" ref={landingFlowBRef}>
            <div className="landing__separator">or</div>
            <GitHubOAuthButton />
          </div>
        </div>

        <div className="landing__trophy">
          <img src="/images/trophy.png" alt="GitHub Wrapped 2022 Trophy" />
        </div>

        <div className="landing__disclaimer">
          *This project is neither maintained nor endorsed by GitHub.
        </div>
      </section>
    </div>
  );
}
